# Generated by Django 2.2.9 on 2020-12-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(default='default.jpeg', upload_to='posts_images'),
        ),
    ]
