# Generated by Django 2.2.9 on 2021-01-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210105_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='biography',
            field=models.CharField(default='My biography', max_length=2000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=models.CharField(default='My Location', max_length=50),
        ),
    ]
